/**
 * The principle that governs each problem.
 *
 * Why this exists: novices file problems by what they look like ("the capacitor one"), experts by
 * the law that decides them (Chi, Feltovich & Glaser). Topic tags index the bank the novice way.
 * These tags index it by principle, so the same law can be shown across chapters and scenarios —
 * a proton accelerated through ΔV, Kirchhoff's loop rule and an RC circuit all answer to
 * conservation of energy.
 *
 * Each template gets one primary principle (what a grader would accept as "the idea") and up to
 * two secondary ones that it also leans on. `conserved` names the conserved quantity, for the
 * "what's conserved here, and what's the system?" question. The primary drives the principle step
 * that opens each practice problem (principle-step.js) and the list's group-by-principle view.
 *
 * Status: drafted from the bank and accepted for FLUX as it stands. If the course adopts FLUX
 * class-wide, the instructor's review (the calls listed in the review page) comes first.
 * problems-check confirms every template is tagged with principles that exist.
 */
export const PRINCIPLES = {
  // --- Conservation laws: the ones that cross every chapter
  charge: {
    name: 'Conservation of charge',
    statement: 'Charge is neither made nor destroyed; it moves. At a junction, current in = current out; charge shared between conductors keeps its total.',
    cue: 'Charge redistributes, splits at a junction, or is shared.',
    conserved: 'charge',
    family: 'Conservation',
  },
  energy: {
    name: 'Conservation of energy',
    statement: 'ΔK + ΔU = W by other forces, with U = qV. Around a closed loop the potential changes add to zero (Kirchhoff’s loop rule); in a transformer, power in = power out.',
    cue: 'Something speeds up or slows down through a potential difference, or you walk around a circuit loop.',
    conserved: 'energy',
    family: 'Conservation',
  },

  // --- Electrostatics
  coulomb: {
    name: 'Coulomb’s law',
    statement: 'Two point charges push or pull along the line between them with F = k|q₁q₂|/r².',
    cue: 'Force between point charges.',
    family: 'Electrostatics',
  },
  superposition: {
    name: 'Superposition',
    statement: 'Forces, fields and potentials from several sources add — vectors as vectors, V as a scalar. A continuous charge is many dq’s: integrate.',
    cue: 'More than one source, or a spread-out charge.',
    family: 'Electrostatics',
  },
  'field-force': {
    name: 'Field as force per charge',
    statement: 'A field acts on a charge placed in it: F = qE (and E = F/q). The sign of q decides the direction.',
    cue: 'A field is given or asked for, and a charge sits in it.',
    family: 'Electrostatics',
  },
  newton: {
    name: 'Newton’s second law with an electric or magnetic force',
    statement: 'ΣF = ma, with the electric or magnetic force as one of the forces: equilibrium when they balance, circular motion when qvB supplies mv²/r.',
    cue: 'Acceleration, hanging or levitating in balance, or moving in a circle.',
    family: 'Mechanics with fields',
  },
  gauss: {
    name: 'Symmetry and Gauss’s law',
    statement: 'Find the symmetry, pick a surface that matches it, then ∮E·dA = Q_enc/ε₀. Only enclosed charge counts.',
    cue: 'Spherical, cylindrical or planar symmetry, or flux through a closed surface.',
    family: 'Electrostatics',
  },
  conductor: {
    name: 'Conductors in equilibrium',
    statement: 'In a conductor at rest E = 0 inside, excess charge sits on the surface, the surface is an equipotential, and E just outside is perpendicular to it.',
    cue: 'A metal object, shell or cavity.',
    family: 'Electrostatics',
  },
  potential: {
    name: 'Potential and its link to the field',
    statement: 'V is potential energy per charge (kq/r for a point charge); ΔV = −∫E·dl, so E = −dV/dx points downhill and is perpendicular to equipotentials.',
    cue: 'Potential, equipotentials, or E from V (or V from E).',
    family: 'Electrostatics',
  },
  capacitance: {
    name: 'Capacitance',
    statement: 'Q = CV, with C set by geometry and dielectric (κε₀A/d for plates); stored energy ½CV². Battery connected fixes V; isolated fixes Q.',
    cue: 'A capacitor, a dielectric, or stored charge and energy.',
    family: 'Circuits',
  },

  // --- Circuits
  ohm: {
    name: 'Current and resistance',
    statement: 'I = dQ/dt; V = IR for an ohmic element; R = ρL/A grows with length and shrinks with area.',
    cue: 'Current, resistance, or a wire’s shape and material.',
    family: 'Circuits',
  },
  power: {
    name: 'Power is energy per time',
    statement: 'P = IV = I²R = V²/R; energy = P·t. For ac, averages use rms values.',
    cue: 'Watts, brightness, heating, or an energy bill.',
    family: 'Circuits',
  },

  // --- Magnetism
  lorentz: {
    name: 'Magnetic force',
    statement: 'F = qv×B on a moving charge and IL×B on a current: perpendicular to both, zero along B, and never does work.',
    cue: 'A charge or current moving through a magnetic field.',
    family: 'Magnetism',
  },
  'biot-savart': {
    name: 'Biot–Savart',
    statement: 'Each current element makes dB ∝ I dl × r̂ / r²; add the pieces. Right-hand rule for the direction.',
    cue: 'B from a wire, loop or arc, without enough symmetry for Ampère.',
    family: 'Magnetism',
  },
  ampere: {
    name: 'Symmetry and Ampère’s law',
    statement: 'Find the symmetry, pick a loop that matches it, then ∮B·dl = μ₀I_enc. Only enclosed current counts.',
    cue: 'A long wire, solenoid or toroid — or the line integral of B itself.',
    family: 'Magnetism',
  },
  magnetism: {
    name: 'Moving charge is the source of magnetism',
    statement: 'All magnetism comes from moving charge and electron spin. Poles always come in N–S pairs; ferromagnets line their domains up with an outside field.',
    cue: 'Magnets, poles, compasses, iron.',
    family: 'Magnetism',
  },
  faraday: {
    name: 'Faraday’s and Lenz’s laws',
    statement: 'A changing magnetic flux makes an emf, ε = −N dΦ_B/dt; the induced current opposes the change (Lenz — energy conservation).',
    cue: 'Anything that changes the flux: moving magnets, sliding bars, rotating coils, changing currents.',
    family: 'Induction',
  },
  inductance: {
    name: 'Self-inductance',
    statement: 'A coil opposes changes in its own current: ε = −L dI/dt; it stores U = ½LI².',
    cue: 'An inductor or solenoid whose current changes.',
    family: 'Induction',
  },
  ac: {
    name: 'AC circuits: reactance and phase',
    statement: 'Capacitors and inductors limit ac through reactance (X_C = 1/ωC, X_L = ωL) and shift phase (ELI the ICE man); Z = √(R² + (X_L − X_C)²).',
    cue: 'An ac source with a capacitor or inductor.',
    family: 'Induction',
  },

  // --- Light
  'em-wave': {
    name: 'Electromagnetic waves',
    statement: 'Light is an EM wave: c = fλ in vacuum, E = cB, and it travels along E × B.',
    cue: 'Wavelength, frequency, field amplitudes, or the spectrum.',
    family: 'Light',
  },
  'wave-energy': {
    name: 'Light carries energy and momentum',
    statement: 'I = ½cε₀E₀² = P/4πr² from a point source; radiation pressure I/c absorbed, 2I/c reflected.',
    cue: 'Intensity, power from a source, or light pushing on something.',
    family: 'Light',
  },
  polarization: {
    name: 'Polarization',
    statement: 'A polarizer passes the field component along its axis: I = I₀cos²θ (half of unpolarized light); reflection at Brewster’s angle polarizes completely.',
    cue: 'Polarizers or polarized reflection.',
    family: 'Light',
  },
  refraction: {
    name: 'Refraction',
    statement: 'Light slows in a medium, v = c/n, with its frequency unchanged; at a boundary n₁sinθ₁ = n₂sinθ₂ (total internal reflection when that has no solution).',
    cue: 'Light crossing into a different material.',
    family: 'Light',
  },
  reflection: {
    name: 'Law of reflection',
    statement: 'The angle of reflection equals the angle of incidence; a plane mirror’s image is as far behind as the object is in front.',
    cue: 'Flat mirrors.',
    family: 'Light',
  },
  imaging: {
    name: 'Image formation',
    statement: 'Rays from one object point meet (or seem to) at one image point: 1/f = 1/d_o + 1/d_i, m = −d_i/d_o; instruments chain images.',
    cue: 'Curved mirrors, lenses, magnifiers, telescopes, the eye.',
    family: 'Light',
  },
  interference: {
    name: 'Interference of waves',
    statement: 'Waves add: a path (or phase) difference of mλ is bright, (m + ½)λ dark. Slits, gratings, thin films and diffraction limits are all this.',
    cue: 'Fringes, slits, gratings, thin films, resolving power.',
    family: 'Light',
  },

  // --- Tools
  vectors: {
    name: 'Vector algebra',
    statement: 'Vectors add by components; the dot product measures how parallel two vectors are, the cross product is perpendicular to both.',
    cue: 'Components, angles, dot or cross products.',
    family: 'Tools',
  },
  density: {
    name: 'Charge density',
    statement: 'Spread-out charge is described per length, area or volume: Q = λL, σA, ρV (or ∫ dq).',
    cue: 'λ, σ or ρ given or asked for.',
    family: 'Tools',
  },
};

/** template id → [primary, ...secondary] */
export const PRINCIPLE_TAGS = {
  // Ch V — vectors
  'e1.v.mag-dir': ['vectors'],
  'e1.v.components': ['vectors'],
  'e1.v.dot': ['vectors'],
  'e1.v.add': ['vectors'],
  'e1.v.cross': ['vectors'],
  'e1.v.dot-sign': ['vectors'],
  // Ch 34 — charge
  'e1.34.electron-count': ['charge'],
  'e1.34.touching-spheres': ['charge', 'conductor'],
  'e1.34.induction': ['charge', 'conductor'],
  'e1.34.polarization': ['coulomb', 'superposition'],
  // Ch 35 — Coulomb
  'e1.35.coulomb-pair': ['coulomb'],
  'e1.35.distance': ['coulomb'],
  'e1.35.three-inline': ['superposition', 'coulomb'],
  'e1.35.equilibrium-point': ['superposition', 'coulomb'],
  'e1.35.right-triangle': ['superposition', 'coulomb', 'vectors'],
  'e1.35.hydrogen': ['coulomb'],
  'e1.35.hanging-spheres': ['newton', 'coulomb'],
  'e1.35.scaling': ['coulomb'],
  // Ch 36A — fields of point charges
  'e2.36a.force-direction': ['field-force'],
  'e2.36a.proton-electron': ['newton', 'field-force'],
  'e2.36a.trajectory': ['newton', 'field-force'],
  'e2.36a.plate-sign': ['field-force'],
  'e2.36a.square-corner': ['superposition', 'vectors'],
  'e2.36a.E-from-force': ['field-force'],
  'e2.36a.accel': ['newton', 'field-force'],
  'e2.36a.E-from-accel': ['newton', 'field-force'],
  'e2.36a.tension': ['newton', 'field-force'],
  'e2.36a.levitate-E': ['newton', 'field-force'],
  'e2.36a.levitate-q': ['newton', 'field-force'],
  'e2.36a.point-field': ['coulomb', 'field-force'],
  'e2.36a.charge-from-field': ['coulomb', 'field-force'],
  'e2.36a.between-two': ['superposition'],
  'e2.36a.collinear': ['superposition'],
  'e2.36a.zero-point': ['superposition'],
  'e2.36a.three-axes': ['superposition', 'vectors'],
  'e2.36a.dipole': ['superposition', 'vectors'],
  // Ch 36B — continuous distributions
  'e2.36b.line-charge-total': ['density'],
  'e2.36b.line-length': ['density'],
  'e2.36b.disk-radius': ['density'],
  'e2.36b.shell-sigma': ['density', 'conductor'],
  'e2.36b.volume-charge': ['density'],
  'e2.36b.rod-bisector': ['superposition', 'density'],
  'e2.36b.ring-axis': ['superposition', 'density'],
  'e2.36b.rod-axis': ['superposition', 'density'],
  'e2.36b.semicircle': ['superposition', 'density'],
  'e2.36b.disk-axis': ['superposition', 'density'],
  // Ch 36C — flux and Gauss
  'e2.36c.zero-flux': ['gauss'],
  'e2.36c.surfaces': ['gauss'],
  'e2.36c.cavity': ['gauss', 'conductor'],
  'e2.36c.hoop-flux': ['gauss', 'vectors'],
  'e2.36c.rect-flux': ['gauss'],
  'e2.36c.hoop-nonuniform': ['gauss'],
  'e2.36c.concentric': ['gauss', 'conductor'],
  'e2.36c.insulating-sphere': ['gauss', 'density'],
  'e2.36c.long-wire': ['gauss', 'density'],
  'e2.36c.sheet': ['gauss', 'superposition'],
  // Ch 37 — conductors
  'e2.37.where-charge-goes': ['conductor'],
  'e2.37.field-inside': ['conductor'],
  'e2.37.empty-cavity': ['conductor', 'gauss'],
  'e2.37.surface-field': ['conductor'],
  'e2.37.cube-induced': ['conductor', 'charge'],
  'e2.37.nested': ['conductor', 'gauss'],
  'e2.37.lightning-cloud': ['conductor', 'charge'],
  'e2.37.lightning-car': ['conductor'],
  // Ch 38 — potential
  'e3.38.point-V': ['potential'],
  'e3.38.work-radial': ['energy', 'potential'],
  'e3.38.uniform-dV': ['potential', 'energy'],
  'e3.38.accelerate': ['energy', 'potential'],
  'e3.38.pair-energy': ['energy', 'potential'],
  'e3.38.system-energy': ['energy', 'superposition'],
  'e3.38.equipotentials': ['potential'],
  'e3.38.E-from-V': ['potential'],
  'e3.38.units-of': ['potential'],
  'e3.38.work-and-deltaV': ['energy', 'potential'],
  'e3.38.field-potential-traps': ['potential'],
  'e3.38.charge-moves': ['energy', 'potential'],
  'e3.38.V-poly-field': ['potential'],
  'e3.38.work-nonuniform': ['potential', 'energy'],
  'e3.38.V-graph': ['potential'],
  'e3.38.V-graph-E': ['potential'],
  'e3.38.V-cubic': ['potential'],
  'e3.38.uniform-path': ['potential', 'energy'],
  'e3.38.pe-rank': ['energy', 'potential'],
  'e3.38.moving-charge-energy': ['energy', 'potential'],
  'e3.38.uniform-rank': ['potential', 'energy'],
  'e3.38.uniform-zero-V': ['potential'],
  // Ch 39 — potential of distributions
  'e3.39.two-charges-V': ['superposition', 'potential'],
  'e3.39.three-charges-V': ['superposition', 'potential'],
  'e3.39.zero-V-point': ['superposition', 'potential'],
  'e3.39.ring-V': ['superposition', 'potential'],
  'e3.39.rod-V': ['superposition', 'potential'],
  'e3.39.sphere-V': ['conductor', 'potential', 'gauss'],
  'e3.39.compare-configs': ['superposition', 'potential'],
  'e3.39.speed-with-v0': ['energy', 'potential'],
  'e3.39.deltaV-two-radii': ['potential'],
  'e3.39.equipotential-map': ['potential', 'energy'],
  'e3.39.equipotential-props': ['potential'],
  'e3.39.sphere-accelerate': ['energy', 'potential'],
  'e3.39.rod-axis-V': ['superposition', 'potential'],
  'e3.39.arc-center-V': ['superposition', 'potential'],
  'e3.39.disk-V': ['superposition', 'potential'],
  // Ch 40 — capacitance
  'e3.40.parallel-plate': ['capacitance', 'potential'],
  'e3.40.dielectric-battery': ['capacitance'],
  'e3.40.C-dielectric': ['capacitance'],
  'e3.40.dielectric-isolated': ['capacitance', 'charge'],
  'e3.40.combo': ['capacitance', 'charge', 'energy'],
  'e3.40.energy': ['capacitance', 'energy'],
  'e3.40.C-for-energy': ['capacitance', 'energy'],
  'e3.40.scaling': ['capacitance'],
  'e3.40.basics': ['capacitance', 'potential'],
  'e3.40.increase-C': ['capacitance'],
  'e3.40.spark-energy': ['capacitance', 'energy'],
  'e3.40.gap-holds': ['potential'],
  'e3.40.paschen-min': ['potential'],
  'e3.40.wider-gap': ['potential'],
  // Ch 41 — current and resistance
  'e3.41.wire-R': ['ohm'],
  'e3.41.temperature': ['ohm'],
  'e3.41.drift': ['ohm', 'charge'],
  'e3.41.charge-flow': ['ohm', 'charge'],
  'e3.41.stretch': ['ohm'],
  'e3.41.non-ohmic': ['ohm'],
  'e3.41.ohm-basics': ['ohm'],
  'e3.41.geometry-concepts': ['ohm'],
  'e3.41.across-resistor': ['ohm', 'potential'],
  'e3.41.block-R': ['ohm'],
  // Ch 42 — power
  'e3.42.bulb': ['power', 'ohm'],
  'e3.42.ac-rms': ['power', 'ohm'],
  'e3.42.cost': ['power', 'energy'],
  'e3.42.two-bulbs': ['power', 'ohm'],
  'e3.42.heater': ['power', 'energy'],
  'e3.42.fuse': ['power', 'charge'],
  'e3.42.grounding': ['ohm', 'potential'],
  'e3.42.body-current': ['ohm'],
  'e3.42.power-basics': ['power', 'ohm'],
  'e3.42.R-from-P-I': ['power', 'ohm'],
  'e3.42.hot-wire': ['power', 'ohm'],
  'e3.42.ac-from-equation': ['power'],
  'e3.42.ac-graph': ['power', 'ohm'],
  'e3.42.concepts': ['power', 'ohm'],
  // Ch 43 — dc circuits
  'e4.43.series': ['energy', 'charge', 'ohm'],
  'e4.43.parallel': ['charge', 'energy', 'ohm'],
  'e4.43.combo': ['energy', 'charge', 'ohm'],
  'e4.43.add-resistor': ['energy', 'charge'],
  'e4.43.series-parallel-ideas': ['charge', 'energy'],
  'e4.43.four-resistors': ['energy', 'charge', 'ohm'],
  'e4.43.parallel-from-total': ['charge', 'energy', 'ohm'],
  'e4.43.bulb-networks': ['charge', 'power'],
  'e4.43.series-pair-series': ['energy', 'charge', 'ohm'],
  'e4.43.branch-currents': ['charge', 'energy', 'ohm'],
  'e4.43.single-loop': ['energy', 'ohm'],
  'e4.43.three-branch': ['energy', 'charge'],
  'e4.43.two-battery-bridge': ['energy', 'charge'],
  // Ch 44 — Kirchhoff, real batteries, RC
  'e4.44.two-loop': ['energy', 'charge'],
  'e4.44.terminal': ['energy', 'ohm', 'power'],
  'e4.44.rc-charge': ['energy', 'capacitance'],
  'e4.44.rc-discharge': ['energy', 'capacitance'],
  'e4.44.rules': ['energy', 'charge'],
  'e4.44.cells-and-bulb': ['energy', 'power'],
  'e4.44.battery-terminal': ['energy', 'power'],
  'e4.44.capacitor-pair': ['capacitance', 'charge', 'energy'],
  'e4.44.rc-limits': ['energy', 'capacitance'],
  'e4.44.rc-from-tau': ['capacitance', 'energy'],
  'e4.44.rc-time-to-V': ['energy', 'capacitance'],
  'e4.44.rc-discharge-state': ['energy', 'capacitance'],
  // Ch 45 — magnetism
  'e4.45.magnets': ['magnetism'],
  'e4.45.sources-materials': ['magnetism'],
  // Ch 46 — magnetic force
  'e4.46.force-mag': ['lorentz'],
  'e4.46.rhr': ['lorentz', 'vectors'],
  'e4.46.circle': ['newton', 'lorentz'],
  'e4.46.selector': ['newton', 'lorentz', 'field-force'],
  'e4.46.wire-force': ['lorentz'],
  'e4.46.spectrometer': ['energy', 'newton', 'lorentz'],
  'e4.46.torque': ['lorentz'],
  'e4.46.what-B-does': ['lorentz', 'energy'],
  'e4.46.page-rhr': ['lorentz', 'vectors'],
  'e4.46.track-sign': ['newton', 'lorentz'],
  'e4.46.force-direction': ['lorentz', 'vectors'],
  'e4.46.qvB-solve': ['lorentz'],
  'e4.46.charge-from-orbit': ['newton', 'lorentz'],
  'e4.46.coil-sides': ['lorentz'],
  'e4.46.spectrometer-mass': ['energy', 'newton', 'lorentz'],
  'e4.46.undeflected': ['newton', 'lorentz', 'field-force'],
  // Ch 47 — B from currents
  'e4.47.long-wire': ['ampere', 'biot-savart'],
  'e4.47.rhr-wire': ['biot-savart'],
  'e4.47.loop': ['biot-savart'],
  'e4.47.solenoid': ['ampere'],
  'e4.47.parallel-wires': ['lorentz', 'ampere'],
  'e4.47.thick-wire': ['ampere'],
  'e4.47.two-wires-B': ['superposition', 'ampere'],
  'e4.47.field-pictures': ['biot-savart', 'lorentz'],
  'e4.47.two-wires-outside': ['superposition', 'ampere'],
  'e4.47.wire-and-loop': ['superposition', 'biot-savart'],
  'e4.47.solenoid-core': ['ampere', 'magnetism'],
  'e4.47.ampere-enclosed': ['ampere'],
  'e4.47.toroid': ['ampere'],
  'e4.47.half-loop': ['biot-savart'],
  // Ch 48 — Faraday and Lenz
  'e5.48.flux': ['faraday', 'vectors'],
  'e5.48.changing-B': ['faraday', 'ohm'],
  'e5.48.bar': ['faraday', 'lorentz', 'energy'],
  'e5.48.lenz': ['faraday', 'energy'],
  'e5.48.expanding': ['faraday'],
  'e5.48.rotate-avg': ['faraday'],
  // Ch 49 — inductance
  'e5.49.solenoid-L': ['inductance', 'ampere'],
  'e5.49.self-emf': ['inductance', 'faraday'],
  'e5.49.rl': ['energy', 'inductance'],
  // Ch 50 — motors, transformers, transmission
  'e5.50.transformer': ['faraday', 'energy'],
  'e5.50.transmission': ['power', 'ohm'],
  'e5.50.motor': ['energy', 'faraday'],
  'e5.50.generator': ['faraday'],
  // Ch 51 — applications
  'e5.51.applications': ['faraday'],
  // Ch 52 — ac circuits
  'e5.52.reactance-C': ['ac', 'capacitance'],
  'e5.52.reactance-L': ['ac', 'inductance'],
  'e5.52.rlc': ['ac', 'power'],
  'e5.52.resonance': ['ac'],
  'e5.52.lead-lag': ['ac'],
  // Ch 53 — EM waves
  'e6.53.f-from-lambda': ['em-wave'],
  'e6.53.B-from-E': ['em-wave'],
  'e6.53.direction': ['em-wave', 'vectors'],
  'e6.53.wave-eq': ['em-wave'],
  // Ch 54 — spectrum
  'e6.54.band': ['em-wave'],
  'e6.54.order': ['em-wave'],
  // Ch 55 — intensity and pressure
  'e6.55.intensity': ['wave-energy'],
  'e6.55.E-from-I': ['wave-energy', 'em-wave'],
  'e6.55.point-source': ['wave-energy', 'energy'],
  'e6.55.pressure': ['wave-energy'],
  // Ch 56 — polarization
  'e6.56.malus-two': ['polarization'],
  'e6.56.malus-three': ['polarization'],
  'e6.56.polarized-in': ['polarization'],
  'e6.56.brewster': ['polarization', 'refraction'],
  // Ch 57 — light in media, plane mirrors
  'e6.57.in-medium': ['refraction', 'em-wave'],
  'e6.57.what-changes': ['refraction', 'em-wave'],
  'e6.57.plane-mirror': ['reflection'],
  'e6.57.two-mirrors': ['reflection'],
  // Ch 58 — refraction
  'e7.58.snell': ['refraction', 'reflection'],
  'e7.58.critical': ['refraction'],
  'e7.58.tir': ['refraction'],
  'e7.58.apparent-depth': ['refraction', 'imaging'],
  'e7.58.dispersion': ['refraction'],
  // Ch 59–62 — images and instruments
  'e7.59.mirror': ['imaging'],
  'e7.59.place-object': ['imaging'],
  'e7.60.lens': ['imaging'],
  'e7.60.power': ['imaging'],
  'e7.60.two-lens': ['imaging'],
  'e7.62.magnifier': ['imaging'],
  'e7.62.telescope': ['imaging'],
  'e7.62.microscope': ['imaging'],
  'e7.62.eye': ['imaging'],
  // Ch 63–65 — wave optics
  'wave.63.double-slit': ['interference'],
  'wave.63.find-lambda': ['interference'],
  'wave.63.dark-angle': ['interference'],
  'wave.63.what-if': ['interference', 'refraction'],
  'wave.63.michelson': ['interference'],
  'wave.64.single-slit': ['interference'],
  'wave.64.grating': ['interference'],
  'wave.64.rayleigh': ['interference'],
  'wave.64.what-if': ['interference'],
  'wave.65.thin-film': ['interference', 'refraction'],
  'wave.65.phase-shift': ['interference', 'refraction'],
};
